# Compilation
FROM docker.io/library/golang:1.20.6-bullseye as build
WORKDIR /app

COPY . .

RUN go build -a -ldflags "-linkmode external -extldflags '-static' -s -w" package-search-api.go

# Runtime
FROM docker.io/library/debian:bullseye-slim

## Get binary
COPY --from=build /app/package-search-api /usr/local/bin/package-search-api

## Start the app
CMD ["package-search-api"]
